### PR TITLE
Drop special-case support for missing keys

### PR DESCRIPTION
**Pull request by zoul**
See #4 for longer discussion and rationale.

I’ve also added a commit that reformats the sources with Prettier – is my Prettier configuration wrong, or were the sources not completely formatted before? (We can drop this part if there’s something off with my Prettier.)

### CODE REVIEW

**Comment by tskj** [comment]
The thing with prettier is that they change the formatting with every version. I usually just accept the churn, but I'm open to locking it down in a config file in the project if you know how.

**Review by tskj — APPROVED** [review]
Thanks for putting this up!

I wonder if it's possible to give a better error message in the case that the key is actually missing and the decoder cannot handle `undefined`. As it stands now you get something like "undefined is not of type string, but of type undefined", which is kind of a weird error message. But I'm also not so sure if we can detect reliably (or explain in a good way to the user) that their decoder does not handle `undefined` and the key is missing (because it can throw for other reasons right?).

If not I will just merge this and take note of it as a potential improvement for later.

**Comment by zoul** [comment]
Prettier – if the formatting changes don’t annoy you, I’m fine with them. (I just wanted to make sure that this wasn’t some kind of formatting war between two incompatible configs :)

As for the error message, I don’t have a better solution now, I’m in favour of merging this and opening a new ticket to improve the error message later. Thank you!

**Comment by tskj** [comment]
Alright, I've made a mental note to improve it, so merge it is! 

I tried formatting it locally on my machine, and it didn't seem to change, so I'm fairly sure this is just prettier having changed its mind.

**Comment by zoul** [comment]
(How soon will this make it to npm? I’ve got some work-in-progress code waiting for it, so I’d love to try it out :) But no pressure!)

**Comment by tskj** [comment]
Should be any minute. Without tests, deploying is very quick ;)

**Pull request merged**
